// Export formatters — plain text, SimplePractice, TherapyNotes, clipboard.

import { invoke, clipboardWriteText } from '../platform/tauri.js';
import { appendAudit } from '../core/auditLog.js';
import { emit } from '../core/eventBus.js';
import { keys } from '../data/keys.js';
import { displayDateShort } from '../utils/format.js';

// Plain text — safe paste into any EHR.
export function toPlainText(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const alias = encounter.patient_alias ? `Patient: ${encounter.patient_alias}\n` : '';
  return `Date: ${date}\n${alias}\n${note}\n`;
}

// SimplePractice — matches their progress note paste structure.
export function toSimplePractice(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Session Date: ${date}`,
    encounter.patient_alias ? `Client: ${encounter.patient_alias}` : '',
    '',
    note,
    '',
    '--- Generated by Tahlk | Provider review and sign-off completed ---',
  ].filter(l => l !== null).join('\n');
}

// TherapyNotes — matches their note import format.
export function toTherapyNotes(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Note Date: ${date}`,
    '',
    note,
    '',
    '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---',
  ].join('\n');
}

// Copy formatted text to the system clipboard.
export async function copyToClipboard(text, encounterId, format) {
  await clipboardWriteText(text);
  appendAudit(keys.noteAudit(encounterId), 'note_exported', { format, method: 'clipboard' });
  emit('scribe:note_exported', { encounterId, format });
}

// Save to a .txt file via the native save dialog.
export async function saveToFile(text, encounter, format) {
  const date = (encounter.encounter_date || '').slice(0, 10).replace(/-/g, '');
  const alias = encounter.patient_alias ? `_${encounter.patient_alias.replace(/\s+/g, '-')}` : '';
  const suggestedName = `note_${date}${alias}.txt`;

  await invoke('export_note_to_file', { content: text, suggestedName });

  appendAudit(keys.noteAudit(encounter.id), 'note_exported', { format, method: 'file' });
  emit('scribe:note_exported', { encounterId: encounter.id, format });
}
