// Export formatters — plain text, SimplePractice, TherapyNotes, clipboard.

import { invoke, clipboardWriteText, clipboardReadText } from '../platform/tauri.js';
import { logNoteExported } from '../core/auditLog.js';
import { emit } from '../core/eventBus.js';
import { displayDateShort } from '../utils/format.js';

// How long copied PHI is allowed to linger on the clipboard before auto-clear.
const CLIPBOARD_CLEAR_MS = 90_000;

// Plain text — safe paste into any EHR.
export function toPlainText(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const alias = encounter.patient_alias ? `Patient: ${encounter.patient_alias}\n` : '';
  return `Date: ${date}\n${alias}\n${note}\n`;
}

// SimplePractice — matches their progress note paste structure.
export function toSimplePractice(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Session Date: ${date}`,
    encounter.patient_alias ? `Client: ${encounter.patient_alias}` : '',
    '',
    note,
    '',
    '--- Generated by Tahlk | Provider review and sign-off completed ---',
  ].filter(l => l !== null).join('\n');
}

// TherapyNotes — matches their note import format.
export function toTherapyNotes(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Note Date: ${date}`,
    '',
    note,
    '',
    '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---',
  ].join('\n');
}

// Copy formatted text to the system clipboard. The note is PHI, so schedule an
// auto-clear — but only wipe the clipboard if it still holds what we wrote, so
// we never clobber something the user copied in the meantime.
//
// _pendingClipboardText tracks what we're waiting to clear so
// clearClipboardOnExit (wired to the window close-requested event in
// entry-solo.js) can run the same check-then-clear immediately if the app
// quits before CLIPBOARD_CLEAR_MS elapses — a plain setTimeout never fires
// once the process exits, so without this, PHI copied shortly before quitting
// stayed on the OS clipboard indefinitely.
let _clipboardClearTimer;
let _pendingClipboardText = null;

async function clearIfStillPending(text) {
  try {
    const current = await clipboardReadText();
    if (current === text) await clipboardWriteText('');
  } catch { /* clipboard unavailable — nothing to clear */ }
}

// Copy sensitive text with the auto-clear guarantee, without assuming the
// text is a clinical note.
//
// Split out of copyToClipboard because recovery codes need exactly this
// protection and none of the note-export bookkeeping: a recovery code is a
// full account-recovery credential for an encrypted PHI database, and
// authScreen.js was calling clipboardWriteText directly, so it sat on the OS
// clipboard indefinitely while a copied note — strictly less powerful — was
// wiped after 90 seconds.
export async function copySensitiveToClipboard(text) {
  await clipboardWriteText(text);
  _pendingClipboardText = text;

  clearTimeout(_clipboardClearTimer);
  _clipboardClearTimer = setTimeout(async () => {
    await clearIfStillPending(text);
    if (_pendingClipboardText === text) _pendingClipboardText = null;
  }, CLIPBOARD_CLEAR_MS);
}

export async function copyToClipboard(text, encounterId, format) {
  await copySensitiveToClipboard(text);
  await logNoteExported(encounterId, format, 'clipboard');
  emit('scribe:note_exported', { encounterId, format });
}

// Best-effort clipboard clear for app-exit time. No-op if nothing is
// currently pending (either nothing was ever copied, or the timed
// auto-clear already ran). Callers should await this before letting the
// window actually close.
export async function clearClipboardOnExit() {
  if (_pendingClipboardText === null) return;
  clearTimeout(_clipboardClearTimer);
  const text = _pendingClipboardText;
  _pendingClipboardText = null;
  await clearIfStillPending(text);
}

// Build a non-PHI export filename. The patient alias is intentionally NOT used:
// it may contain a real name, and filenames leak via listings, backups, and
// recent-files. The encounter id is a non-PHI slug; identification lives in the
// note content, not the filename.
export function exportFilename(encounter, ext = 'txt') {
  const date = (encounter.encounter_date || '').slice(0, 10).replace(/-/g, '');
  const id = String(encounter.id || '').replace(/[^A-Za-z0-9_-]/g, '');
  return `note_${date || 'undated'}_${id || 'note'}.${ext}`;
}

// Save to a .txt file via the native save dialog.
export async function saveToFile(text, encounter, format) {
  await invoke('export_note_to_file', { content: text, suggestedName: exportFilename(encounter) });

  await logNoteExported(encounter.id, format, 'file');
  emit('scribe:note_exported', { encounterId: encounter.id, format });
}
