// Export formatters — plain text, SimplePractice, TherapyNotes, clipboard.

import { invoke, clipboardWriteText, clipboardReadText } from '../platform/tauri.js';
import { logNoteExported } from '../core/auditLog.js';
import { emit } from '../core/eventBus.js';
import { displayDateShort } from '../utils/format.js';

// How long copied PHI is allowed to linger on the clipboard before auto-clear.
const CLIPBOARD_CLEAR_MS = 90_000;

// Every exported note must disclose that it was AI-assisted and provider-
// attested (finding S6). Emerging state AI-transparency rules (e.g. California
// AB 3030) expect generative-AI clinical documentation to be identifiable as
// such; the label also matches the PDF export footer. Kept as shared constants
// so the wording cannot drift between formats — previously the plain-text
// export carried NO disclosure and the SimplePractice one said "Generated by
// Tahlk" without naming AI at all.
const AI_DISCLOSURE = '--- Tahlk (AI-assisted) | Reviewed and attested by provider ---';
const AI_DISCLOSURE_SP = '--- Tahlk (AI-assisted) | Provider review and sign-off completed ---';

// Plain text — safe paste into any EHR.
export function toPlainText(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  const alias = encounter.patient_alias ? `Patient: ${encounter.patient_alias}\n` : '';
  return `Date: ${date}\n${alias}\n${note}\n\n${AI_DISCLOSURE}\n`;
}

// SimplePractice — matches their progress note paste structure.
export function toSimplePractice(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Session Date: ${date}`,
    // null, not '', so the filter below actually drops the line. It emitted
    // '' — which the `!== null` filter never matched — so an encounter with
    // no alias produced a stray blank line where "Client:" would have been.
    // The two bare '' entries are deliberate spacing and must survive, which
    // is why the filter tests for null rather than falsiness.
    encounter.patient_alias ? `Client: ${encounter.patient_alias}` : null,
    '',
    note,
    '',
    AI_DISCLOSURE_SP,
  ].filter(l => l !== null).join('\n');
}

// TherapyNotes — matches their note import format.
export function toTherapyNotes(note, encounter) {
  const date = displayDateShort(encounter.encounter_date || encounter.created_at);
  return [
    `Note Date: ${date}`,
    '',
    note,
    '',
    AI_DISCLOSURE,
  ].join('\n');
}

// Copy formatted text to the system clipboard. The note is PHI, so schedule an
// auto-clear — but only wipe the clipboard if it still holds what we wrote, so
// we never clobber something the user copied in the meantime.
//
// _pendingClipboardText tracks what we're waiting to clear so
// clearClipboardOnExit (wired to the window close-requested event in
// entry-solo.js) can run the same check-then-clear immediately if the app
// quits before CLIPBOARD_CLEAR_MS elapses — a plain setTimeout never fires
// once the process exits, so without this, PHI copied shortly before quitting
// stayed on the OS clipboard indefinitely.
let _clipboardClearTimer;
let _pendingClipboardText = null;

async function clearIfStillPending(text) {
  try {
    const current = await clipboardReadText();
    if (current === text) await clipboardWriteText('');
  } catch { /* clipboard unavailable — nothing to clear */ }
}

// Copy sensitive text with the auto-clear guarantee, without assuming the
// text is a clinical note.
//
// Split out of copyToClipboard because recovery codes need exactly this
// protection and none of the note-export bookkeeping: a recovery code is a
// full account-recovery credential for an encrypted PHI database, and
// authScreen.js was calling clipboardWriteText directly, so it sat on the OS
// clipboard indefinitely while a copied note — strictly less powerful — was
// wiped after 90 seconds.
export async function copySensitiveToClipboard(text) {
  await clipboardWriteText(text);
  _pendingClipboardText = text;

  clearTimeout(_clipboardClearTimer);
  _clipboardClearTimer = setTimeout(async () => {
    await clearIfStillPending(text);
    if (_pendingClipboardText === text) _pendingClipboardText = null;
  }, CLIPBOARD_CLEAR_MS);
}

export async function copyToClipboard(text, encounterId, format) {
  await copySensitiveToClipboard(text);
  await logNoteExported(encounterId, format, 'clipboard');
  emit('scribe:note_exported', { encounterId, format });
}

// Best-effort clipboard clear for app-exit time. No-op if nothing is
// currently pending (either nothing was ever copied, or the timed
// auto-clear already ran). Callers should await this before letting the
// window actually close.
export async function clearClipboardOnExit() {
  if (_pendingClipboardText === null) return;
  clearTimeout(_clipboardClearTimer);
  const text = _pendingClipboardText;
  _pendingClipboardText = null;
  await clearIfStillPending(text);
}

// Build a non-PHI export filename. The patient alias is intentionally NOT used:
// it may contain a real name, and filenames leak via listings, backups, and
// recent-files. The encounter id is a non-PHI slug; identification lives in the
// note content, not the filename.
export function exportFilename(encounter, ext = 'txt') {
  const date = (encounter.encounter_date || '').slice(0, 10).replace(/-/g, '');
  const id = String(encounter.id || '').replace(/[^A-Za-z0-9_-]/g, '');
  return `note_${date || 'undated'}_${id || 'note'}.${ext}`;
}

// Save to a .txt file via the native save dialog.
//
// Returns true only if a file was actually written; false means the provider
// dismissed the dialog. The audit entry and the event are gated on that: a
// cancelled export is not a disclosure, and recording one puts a note_exported
// row in the trail for PHI that never left the app. That matters beyond
// tidiness — the export log is what a breach assessment reads to decide who to
// notify under §164.404, so a phantom row means notifying an individual about a
// disclosure that did not happen (M-1).
export async function saveToFile(text, encounter, format) {
  const saved = await invoke('export_note_to_file', {
    content: text,
    suggestedName: exportFilename(encounter),
  });
  if (!saved) return false;

  await logNoteExported(encounter.id, format, 'file');
  emit('scribe:note_exported', { encounterId: encounter.id, format });
  return true;
}
